app1/urls.py
from django.urls import path
from app1.views import *
app_name='impossible'
urlpatterns=[
    path('impossible/',impossible,name='impossible'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='possible'
urlpatterns=[
    path('possible/',possible,name='possible'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def impossible(request):
    return render(request,'impossible.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def possible(request):
    return render(request,'possible.html')

templates/impossible.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center> 
        <h1>NOTHING IS IMPOSSIBLE</h1>
        <h3><a href="{% url 'possible:possible' %}">possible says that</a></h3>
    </center>
</body>
</html>

templates/possible.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>"THE WORD ITSELF SAYS I'M POSSIBLE!"</h1>
        <h3><a href="{% url 'impossible:impossible' %}">go to impossible</a></h3>
    </center>
</body>
</html>